apiVersion: v1
kind: Service
metadata:
  labels:
    name: java-api-svc
  name: java-api
spec:
  externalIPs:
    - 192.168.1.81
  ports:
    # the port that this service should serve on
    - port: 5000
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: java-api
